# Generated by Django 5.1.1 on 2024-10-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=100)),
                ('member_1', models.CharField(default='', max_length=100)),
                ('member_2', models.CharField(default='', max_length=100)),
                ('member_3', models.CharField(default='', max_length=100)),
                ('member_4', models.CharField(default='', max_length=100)),
                ('ph_no', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
