# Generated by Django 5.1.1 on 2024-10-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member_1',
            new_name='player_1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member_2',
            new_name='player_2',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member_3',
            new_name='player_3',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='member_4',
            new_name='player_4',
        ),
    ]
