# Generated by Django 4.2.10 on 2024-10-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_member_1_team_player_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='BGMI_Team',
        ),
    ]
